export const BLOCK = {
  CREATE: 'ACTION_CREATE_BLOCK',
  UPDATE: 'ACTION_UPDATE_BLOCK',
  MINE: 'ACTION_MINE_BLOCK',
  VERIFY: 'ACTION_VERIFY_BLOCK',
  CALCULATE_HASH: 'ACTION_CALCULATE_HASH_BLOCK',
};
